FROM ubuntu:24.04

ARG RUNWAY_USER=runway
ARG RUNWAY_ROOT=/opt/runway
ARG RUNWAY_CHECKOUT="$RUNWAY_ROOT/checkout"

WORKDIR $RUNWAY_ROOT

ENV RUNWAY_SSH_KNOWN_HOSTS_FILE=
ENV RUNWAY_SSH_KNOWN_HOSTS=
ENV RUNWAY_SSH_KEY_FILE=
ENV RUNWAY_SSH_KEY=
ENV RUNWAY_REPO=
ENV RUNWAY_BRANCH=
ENV RUNWAY_UPDATE_DELAY=60


RUN apt-get update && apt-get --yes install git && \
	useradd -M "$RUNWAY_USER" && chown -R "$RUNWAY_USER":"$RUNWAY_USER" "$RUNWAY_ROOT"

COPY entrypoint.sh "$RUNWAY_ROOT"

USER runway
ENTRYPOINT ["/bin/sh"]
CMD ["$RUNWAY_ROOT/entrypoint.sh"]
